name: GitHub Actions

on: push

env:
  REPO: lazerg/laravel
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Run build script
        run: |
          chmod +x ./path_to_your_script/your_script.sh
          ./path_to_your_script/your_script.sh