name: GitHub Actions

on: push

env:
  REPO: lazerg/laravel
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: chmod +x ./build.sh && ./build.sh